### ISSUE TITLE
How to pay with new wallet?

### ISSUE THREAD

**Issue by MoeCasts** [bavix/laravel-wallet#25] opened 2019-05-12 17:17 UTC
There are multi wallets in the app, how to pay with the right wallet?

**Comment by rez1dent3** [comment] 2019-05-12 18:39
@MoeCasts 

new wallet:
```php
$usd = $user->createWallet(['name' => 'USD']);
// todo deposit
$usd->pay($product);
```

find wallet:
```php
$usd = $user->getWallet('usd'); // find by slug
$usd->pay($product);
```

![Снимок экрана от 2019-05-12 21-36-03](https://user-images.githubusercontent.com/5111255/57586401-05d6f700-74fe-11e9-8937-5a3509a5ac0c.png)

**Comment by rez1dent3** [comment] 2019-05-12 19:05
@MoeCasts I have noticed that the Commission is considered not true. Soon to be fixed....

**Comment by MoeCasts** [comment] 2019-05-13 04:06
@rez1dent3 I have got that, when I pay with the user's second wallet, the product default wallet will get the money. Also, the transfer from_type will be the Wallet Class, it should be the User Class, and the transfer status is 'gift' which should be 'paid.

**Comment by rez1dent3** [comment] 2019-05-13 09:27
@MoeCasts Yes, the bug is there.
Really should go into the status "paid". But the goods have to be fixed to a wallet, it works correctly.

In PR #30 I made changes to the project.

**Comment by rez1dent3** [comment] 2019-05-13 09:52
@MoeCasts fixes in tag 2.3.0. One migration was added.

**Comment by MoeCasts** [comment] 2019-05-13 13:00
@rez1dent3 I got this error after upgraded. Is that a wrong in the package?
![image](https://user-images.githubusercontent.com/37169906/57623222-e6a19d80-75c1-11e9-830f-48489c8e8c28.png)

**Comment by rez1dent3** [comment] 2019-05-13 13:02
@MoeCasts funnily... I'll try to catch it. I didn't have one of those.

**Comment by rez1dent3** [comment] 2019-05-13 13:08
@MoeCasts added doctrine/dbal depending. the problem should disappear... tag 2.3.1

**Comment by MoeCasts** [comment] 2019-05-13 13:09
@rez1dent3 Yes, I have just found that. Thank you very much!

**Comment by MoeCasts** [comment] 2019-05-13 13:15
@rez1dent3 There is a new error. And I solved it by added that to the new migration.
`Schema::getConnection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');`
![image](https://user-images.githubusercontent.com/37169906/57624209-0f2a9700-75c4-11e9-9aac-155de7bc64f7.png)

**Comment by rez1dent3** [comment] 2019-05-13 13:27
@MoeCasts able to reproduce...

**Comment by MoeCasts** [comment] 2019-05-13 13:38
@rez1dent3 Will you add this to the package?

**Comment by rez1dent3** [comment] 2019-05-13 13:39
@MoeCasts yes

**Comment by MoeCasts** [comment] 2019-05-13 14:04
@rez1dent3 Thank you very much!

**Comment by rez1dent3** [comment] 2019-05-13 14:23
@MoeCasts done. see the tag 2.3.2

**Comment by MoeCasts** [comment] 2019-05-13 15:37
@rez1dent3 There is a problem, when I pay with new wallet, the transfer's from_type and from_id is wallet class and id, it would cause that `$user->paid($product) ` will not be work. Also, Both User and Product have two wallets. When user pay with default wallet and new wallet, only the product default will get the money. In my opinion, the same slug wallet should get the money.

![image](https://user-images.githubusercontent.com/37169906/57634168-58381680-75d7-11e9-843f-51559c66d4f0.png)

![image](https://user-images.githubusercontent.com/37169906/57634477-f5934a80-75d7-11e9-816e-be702127d4d8.png)

![image](https://user-images.githubusercontent.com/37169906/57633390-19559100-75d6-11e9-9540-d1254a057a29.png)

**Comment by MoeCasts** [comment] 2019-05-13 15:40
@rez1dent3 There is a problem, when I pay with new wallet, the transfer's from_type and from_id is wallet class and id, it would cause that `$user->paid($product) ` will not be work. Also, Both User and Product have two wallets. When user pay with default wallet and new wallet, only the product default will get the money. In my opinion, the same slug wallet should get the money.

![image](https://user-images.githubusercontent.com/37169906/57634168-58381680-75d7-11e9-843f-51559c66d4f0.png)

![image](https://user-images.githubusercontent.com/37169906/57634477-f5934a80-75d7-11e9-816e-be702127d4d8.png)

![image](https://user-images.githubusercontent.com/37169906/57633390-19559100-75d6-11e9-9540-d1254a057a29.png)

**Comment by rez1dent3** [comment] 2019-05-13 15:48
@MoeCasts The user is a wallet, so when you buy a product is assigned to him. This feature is necessary for the implementation of the return (refund) of goods.

**Comment by rez1dent3** [comment] 2019-05-13 15:49
@MoeCasts  You can inherit from Wallet and add relations.

**Comment by MoeCasts** [comment] 2019-05-13 16:06
@rez1dent3 I try to get the new wallet transfers, but it only return the default wallet transfers. Is it wrong?
![image](https://user-images.githubusercontent.com/37169906/57636498-d5fe2100-75db-11e9-9749-e51e9a06c7e5.png)
![image](https://user-images.githubusercontent.com/37169906/57636359-91728580-75db-11e9-8cec-6196456e3fa9.png)
![image](https://user-images.githubusercontent.com/37169906/57633390-19559100-75d6-11e9-9540-d1254a057a29.png)

**Comment by rez1dent3** [comment] 2019-05-13 19:18
@MoeCasts 
Branch **2.4.x-dev**

```bash
composer req bavix/laravel-wallet:2.4.x-dev
```

Simple:
```php
    $user = \App\User::first();
    $user->load('wallets.transfers');

    $item = \App\Item::first();
    $usd = $user->getWallet('usd');
    $usd->pay($item);  // first 

    $user->wallet->pay($item); // payment by default wallet
    $usd->pay($item); // payment with new wallet
```

Result:
```json
{
   "id":1,
   "name":"Arch Schaden",
   "email":"dyost@example.com",
   "email_verified_at":"2019-05-13 18:28:23",
   "created_at":"2019-05-13 18:28:23",
   "updated_at":"2019-05-13 18:28:23",
   "wallets":[
      {
         "id":1,
         "holder_type":"App\\User",
         "holder_id":1,
         "name":"Default Wallet",
         "slug":"default",
         "description":null,
         "balance":238832,
         "created_at":"2019-05-13 18:30:40",
         "updated_at":"2019-05-13 18:45:25",
         "transfers":[
            {
               "id":3,
               "from_type":"Bavix\\Wallet\\Models\\Wallet",
               "from_id":1,
               "to_type":"App\\Item",
               "to_id":1,
               "status":"paid",
               "status_last":null,
               "deposit_id":9,
               "withdraw_id":8,
               "fee":0,
               "uuid":"d52fb86e-37b8-4b5f-994c-ca1cd986bb78",
               "created_at":"2019-05-13 18:45:25",
               "updated_at":"2019-05-13 18:45:25"
            }
         ]
      },
      {
         "id":3,
         "holder_type":"App\\User",
         "holder_id":1,
         "name":"EUR",
         "slug":"eur",
         "description":null,
         "balance":716496,
         "created_at":"2019-05-13 18:30:40",
         "updated_at":"2019-05-13 18:35:43",
         "transfers":[

         ]
      },
      {
         "id":2,
         "holder_type":"App\\User",
         "holder_id":1,
         "name":"USD",
         "slug":"usd",
         "description":null,
         "balance":238832,
         "created_at":"2019-05-13 18:30:40",
         "updated_at":"2019-05-13 18:45:25",
         "transfers":[
            {
               "id":2,
               "from_type":"Bavix\\Wallet\\Models\\Wallet",
               "from_id":2,
               "to_type":"App\\Item",
               "to_id":1,
               "status":"paid",
               "status_last":null,
               "deposit_id":7,
               "withdraw_id":6,
               "fee":0,
               "uuid":"ef6b6a71-b375-4d07-b2a3-98f3b1491f96",
               "created_at":"2019-05-13 18:41:35",
               "updated_at":"2019-05-13 18:41:35"
            },
            {
               "id":4,
               "from_type":"Bavix\\Wallet\\Models\\Wallet",
               "from_id":2,
               "to_type":"App\\Item",
               "to_id":1,
               "status":"paid",
               "status_last":null,
               "deposit_id":11,
               "withdraw_id":10,
               "fee":0,
               "uuid":"52289967-76c0-4cdc-ae25-0583b12e83df",
               "created_at":"2019-05-13 18:45:25",
               "updated_at":"2019-05-13 18:45:25"
            }
         ]
      }
   ]
}
```

**Comment by MoeCasts** [comment] 2019-05-14 05:17
@rez1dent3 I found that, the `$user->wallet` will return the first wallet of the user but not the default wallet of user. So I think that there should be a select in the wallet relation like this:

```
public function wallet(): MorphOne
{
    return ($this instanceof WalletModel ? $this->holder : $this)
        ->morphOne(config('wallet.wallet.model'), 'holder')
        ->where('slug', config('wallet.wallet.default.slug'))
        ->withDefault([
            'name' => config('wallet.wallet.default.name'),
            'slug' => config('wallet.wallet.default.slug'),
            'balance' => 0,
        ]);
}
```

**Comment by rez1dent3** [comment] 2019-05-14 05:32
@MoeCasts Here the default wallet will return, you can check.

**Comment by MoeCasts** [comment] 2019-05-14 06:00
@rez1dent3 The `paid` function is still not work with the new wallet.  I have solved by this code. Is there any help for your improvement?
```
public function payForPlan(Wallet $wallet, Product $product, $type = 'subscribe', bool $force = false): Transfer
{
    if (!$product->canBuy($this, $force)) {
        throw new ProductEnded(trans('wallet::errors.product_stock'));
    }

    $amount = $product->getAmountProduct($type);

    $productWallet = $product->getWallet($wallet->slug);

    if ($force) {
        return $wallet->forceTransfer(
            $productWallet,
            $amount,
            $product->getMetaProduct(),
            Transfer::STATUS_PAID
        );
    }

    return $wallet->transfer(
        $productWallet,
        $amount,
        $product->getMetaProduct(),
        Transfer::STATUS_PAID
    );
}

public function paidForPlan(Wallet $wallet, Product $product, bool $gifts = false): ?Transfer
{
    $status = [Transfer::STATUS_PAID];
    if ($gifts) {
        $status[] = Transfer::STATUS_GIFT;
    }

    $productWallet = $product->getWallet($wallet->slug);

    /**
     * @var Model $product
     * @var Transfer $query
     */
    // dd($productWallet);
    $query = $wallet->transfers();
    return $query
        ->where('to_type', $productWallet->getMorphClass())
        ->where('to_id', $productWallet->getKey())
        ->whereIn('status', $status)
        ->orderBy('id', 'desc')
        ->first();
}
```

**Comment by MoeCasts** [comment] 2019-05-14 06:18
@rez1dent3 In my opinion, the transfers table should not have from_type and to_type columns, we can get the holder without that columns.

**Comment by rez1dent3** [comment] 2019-05-14 09:12
@MoeCasts Initially, the wallet was developed for yourself and without the ability to work with many wallets. Because of this, such a structure was chosen. It works for many wallets, but the goods will be assigned to the wallet.

In the next versions, I plan to implement a verification feature similar to yours, but it should be done more accurately and abstractly.

PS,
All wishes for version 3.0, you can write here #18

**Comment by MoeCasts** [comment] 2019-05-14 10:44
@rez1dent3 Sorry what's the meaning of `the goods will be assigned to the wallet.`?  I can't understand it.

**Comment by rez1dent3** [comment] 2019-05-14 10:48
@MoeCasts 
When buying a product in the database, will be assigned to the wallet. Not per user. If you check the ' paid` method of the wallet, the result will be TRUE.

```php
$user->wallet->pay($item);
$user->paid($item); // false
$user->wallet->pay($item); // true
```

**Comment by rez1dent3** [comment] 2019-05-14 10:51
@MoeCasts 
The peculiarity of the wallets.

At the moment there can be 2 solutions.
1. You create a table and store the data yourself.
2. Add a link and pull data from all wallets, then it will work.

**Comment by MoeCasts** [comment] 2019-05-14 10:57
> @MoeCasts Here the default wallet will return, you can check.

I checked，it did't return the default wallet.

Code:
```
public function wallet(): MorphOne
{
    return ($this instanceof WalletModel ? $this->holder : $this)
        ->morphOne(config('wallet.wallet.model'), 'holder')
        // ->where('slug', config('wallet.wallet.default.slug'))
        ->withDefault([
            'name' => config('wallet.wallet.default.name'),
            'slug' => config('wallet.wallet.default.slug'),
            'balance' => 0,
        ]);
}
```
Result:
```
[
    {
        "id": 2,
        "holder_type": "App\\Models\\User",
        "holder_id": 11,
        "name": "喵粮",
        "slug": "coins",
        "description": null,
        "balance": 206004,
        "created_at": "2019-05-13 22:57:16",
        "updated_at": "2019-05-14 13:56:19"
    }
]
```
But the default wallet is
```
[
    {
        "id": 1,
        "holder_type": "App\\Models\\User",
        "holder_id": 11,
        "name": "积分",
        "slug": "points",
        "description": null,
        "balance": 53300,
        "created_at": "2019-05-13 22:57:16",
        "updated_at": "2019-05-14 13:30:14"
    }
]
```
Here is the data
![image](https://user-images.githubusercontent.com/37169906/57692566-abfb3c00-7679-11e9-9e7f-d8e7bd00765d.png)

**Comment by rez1dent3** [comment] 2019-05-14 11:01
@MoeCasts I can replace it with $this, it won't break anything. need to?

**Comment by MoeCasts** [comment] 2019-05-14 11:03
@rez1dent3 just need to add this code `->where('slug', config('wallet.wallet.default.slug'))`, the problem will be solved. That's won't break anything too.

**Comment by rez1dent3** [comment] 2019-05-14 11:21
@MoeCasts Okay I will try. Thank you.

**Comment by MoeCasts** [comment] 2019-05-14 12:03
@rez1dent3 thank you very much!

**Comment by rez1dent3** [comment] 2019-05-14 12:05
@MoeCasts done. branch 2.4.x-dev

**Comment by rez1dent3** [comment] 2019-05-14 18:28
@MoeCasts Edits made. Use the 2.4.0 tag. Thank you.

**Closed by rez1dent3** 2019-05-14 18:28 UTC
Labels: good first issue
