### ISSUE TITLE
ErrorException Trying to get property 'exists' of non-object

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#245] opened 2020-10-13 15:36 UTC
this error comes out when i try to display user balance

**Comment by rez1dent3** [comment] 2020-10-13 18:37
Hello. I need some code and trace information (complete).

**Comment by odion-cloud** [comment] 2020-10-13 19:53
> Hello. I need some code and trace information (complete).

this error comes out after  deposit into new user default wallet

**Comment by odion-cloud** [comment] 2020-10-13 20:00
if ($autoSave) {

            $wallet->exists or $wallet->save();

        }

**Comment by rez1dent3** [comment] 2020-10-14 15:53
I can't help without the code and trace. I can't reproduce...

**Comment by rez1dent3** [comment] 2020-10-22 15:26
@odion-cloud Will there be an example?

**Comment by rez1dent3** [comment] 2020-10-28 17:15
No more questions. I am closing the issue. There will be questions - reopen or create a new one.

**Comment by asadullah097** [comment] 2020-11-19 22:13
![image](https://user-images.githubusercontent.com/38780235/99730425-3bd73d00-2ade-11eb-8e46-cf0b64e80644.png)
![image](https://user-images.githubusercontent.com/38780235/99730448-47c2ff00-2ade-11eb-902f-6fb7b34567fa.png)
I just installed wallet 5.3 and i just testing at it give me this error

**Comment by rez1dent3** [comment] 2020-11-20 16:30
@asadullah097 Now I tried to install version 5.3.1, there are no such problems. Please provide laravel version, php and exact laravel wallet version (including patch).

Also, the complete user model. There may be conflicts with other packages (in theory).

**Comment by asadullah097** [comment] 2020-11-20 16:34
Thank you for replying to me i already used in two other projects but i never faced this issue currently I am in laravel 7*and the PHP version is 7.4 and wallet version is 5.3

**Comment by rez1dent3** [comment] 2020-11-20 16:40
And also write the database you are using: Postgres, MySQL.

Have you tried updating the library, at least to version [5.5.1](https://github.com/bavix/laravel-wallet/releases/tag/5.5.1)? Better up to [6.0.1](https://github.com/bavix/laravel-wallet/releases/tag/6.0.1)

**Comment by asadullah097** [comment] 2020-11-20 16:41
Mysql and let try the new  version 5.5.1

**Comment by rez1dent3** [comment] 2020-11-20 16:45
@asadullah097 
laravel: 7.26.1
laravel wallet: 5.3.0
mysql: 8.0.20
php: 7.4.12

This error cannot be reproduced ... Could you make a test project with an error and upload it to github?

**Comment by asadullah097** [comment] 2020-11-20 16:53
@rez1dent3 sure

**Comment by asadullah097** [comment] 2020-11-20 21:45
@rez1dent3 
same requirements but give me the same error

**Comment by odion-cloud** [comment] 2020-11-24 12:35
same error

**Comment by rez1dent3** [comment] 2020-11-25 15:43
@odion-cloud can you make a test project on github in a docker container? If there is an error in docker, then I can fix it.

At the moment, I cannot identify the problem, perhaps the problem is in certain settings, environment, etc.

**Comment by odion-cloud** [comment] 2020-11-27 08:52
this method worked for transfer

        $first = User::find(auth()->user()->id);
        $firstWallet = $first->getWallet('default'); 
        
        $last = User::where('id','=',$request->id)->first(); // last user
        $lastWallet = $last->getWallet('default');

        $firstWallet->getKey() !== $lastWallet->getKey(); // true 
            
        $firstWallet->transfer($lastWallet, (int)$request->amount);
       
        return redirect()->back()->with('success','transfer was successful');

**Comment by odion-cloud** [comment] 2020-11-27 08:53
> this method worked for transfer
> 
> ```
>     $first = User::find(auth()->user()->id);
>     $firstWallet = $first->getWallet('default'); 
>     
>     $last = User::where('id','=',$request->id)->first(); // last user
>     $lastWallet = $last->getWallet('default');
> 
>     $firstWallet->getKey() !== $lastWallet->getKey(); // true 
>         
>     $firstWallet->transfer($lastWallet, (int)$request->amount);
>    
>     return redirect()->back()->with('success','transfer was successful');
> ```

after getting the user then get the particular wallet of the user you are tranfering to!

**Comment by rez1dent3** [comment] 2020-11-27 09:15
@odion-cloud 
Thanks. I understood what the problem is.

I did not add a check and gave the opportunity to shoot myself in the foot. The point is that the `getWallet` method can return null, and you have no validation in your code.

Most likely, the first user has a wallet, while the second does not. Try adding the following code:

```php
if ($lastWallet === null) {
    $lastWallet = $last->wallet;
}
```

In future versions, I will close the ability to get a null value with this method and add a new method that will create the wallet if it does not exist (to reduce the code on your side).

**Comment by odion-cloud** [comment] 2020-11-27 09:26
> @odion-cloud
> Thanks. I understood what the problem is.
> 
> I did not add a check and gave the opportunity to shoot myself in the foot. The point is that the `getWallet` method can return null, and you have no validation in your code.
> 
> Most likely, the first user has a wallet, while the second does not. Try adding the following code:
> 
> ```
> if ($lastWallet === null) {
>     $lastWallet = $last->wallet;
> }
> ```
> 
> In future versions, I will close the ability to get a null value with this method and add a new method that will create the wallet if it does not exist (to reduce the code on your side).
> 
> PS, similarly for firstUser

thank alot best wallet

**Comment by rez1dent3** [comment] 2020-11-28 19:44
@odion-cloud  Added the getWalletOrFail method. If there is no wallet model, then the method will return an error. This will save many from this problem.
see tag: 6.0.2

**Comment by asadullah097** [comment] 2020-11-29 05:03
@rez1dent3 this error is not the error of the package this is due to some custom methods is defined in your Model such as wallet, balance, etc. my error was the same custom-defined methods. the other developer-defined a method wallet now I rename the custom wallet method and the error is fixed

**Comment by rez1dent3** [comment] 2020-11-30 17:02
@odion-cloud Most likely this is not the correct use of the package, you did not provide an example to me. I close the Issue.
@asadullah097 Thank you.

**Closed by rez1dent3** 2020-11-30 17:02 UTC
Labels: enhancement, question, wontfix
